extends:
  [
    'eslint:recommended',
    'plugin:@typescript-eslint/eslint-recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:@typescript-eslint/recommended-requiring-type-checking',
    'prettier',
    'plugin:import/warnings',
    'plugin:import/errors',
    'plugin:import/typescript',
  ]
plugins: ['@typescript-eslint', 'prettier', 'import']
env:
  browser: false
  es6: true
  node: false
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2021
  sourceType: module
  project: 'tsconfig.json'
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: true
  semi:
    - error
    - never
  object-curly-spacing:
    - warn
    - always
  import/order:
    - error
  'no-unused-expressions': 'off'
  '@typescript-eslint/no-unused-expressions': 'warn'
  '@typescript-eslint/no-unsafe-assignment': 'off'
  '@typescript-eslint/no-empty-function': 'warn'
  '@typescript-eslint/no-non-null-assertion': 'off'
  '@typescript-eslint/no-extra-non-null-assertion': 'off'
  '@typescript-eslint/no-unnecessary-type-assertion': 'off'
  '@typescript-eslint/no-unsafe-member-access': 'off'
  '@typescript-eslint/no-unsafe-call': 'off'
  "prefer-const": "off"
